// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAWia0hnxL0iMxgydyXjoi4gjcfZNSDjto',
    appId: '1:788770650988:web:1b95e29104ca2b8d1d5149',
    messagingSenderId: '788770650988',
    projectId: 'sun-societies',
    authDomain: 'sun-societies.firebaseapp.com',
    storageBucket: 'sun-societies.appspot.com',
    measurementId: 'G-C5ESJH1LYS',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC19OzmJrNOC7VD2ZjbBhrvJGiJ4p0dRWM',
    appId: '1:788770650988:android:4c56a4a0e087c8281d5149',
    messagingSenderId: '788770650988',
    projectId: 'sun-societies',
    storageBucket: 'sun-societies.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyArsd0MK32V5XjO5JH8AItb9kb1BdHQBy0',
    appId: '1:788770650988:ios:62f3684e34b23c161d5149',
    messagingSenderId: '788770650988',
    projectId: 'sun-societies',
    storageBucket: 'sun-societies.appspot.com',
    androidClientId:
        '788770650988-v5tvk2ita3tpcmen6cd9sr7sc2v9i18h.apps.googleusercontent.com',
    iosBundleId: 'com.one.flutterApplication',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyArsd0MK32V5XjO5JH8AItb9kb1BdHQBy0',
    appId: '1:788770650988:ios:46be65933de0725f1d5149',
    messagingSenderId: '788770650988',
    projectId: 'sun-societies',
    storageBucket: 'sun-societies.appspot.com',
    androidClientId:
        '788770650988-v5tvk2ita3tpcmen6cd9sr7sc2v9i18h.apps.googleusercontent.com',
    iosBundleId: 'com.one.flutterApplication.RunnerTests',
  );
}
